name: RunBenchmarks
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'liberica'
          architecture: x64

      - name: Build benchmarks
        run: ./gradlew mainBenchmarkJar

      - name: Run benchmarks
        run: |
          OUT_FILE_NAME=$(date "+%Y-%m-%dT%H%M%S-linux-x64-"$(git rev-parse --short HEAD)".json")
          test -d results || mkdir results
          java -jar ./build/benchmarks/main/jars/stdlib-signum-main-jmh-1.0-SNAPSHOT-JMH.jar -f2 -rf json -tu ns -bm avgt -rff results/$OUT_FILE_NAME

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'
