name: RunBenchmarks
on:
  workflow_dispatch:

jobs:
  jvm:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'liberica'
          architecture: x64

      - name: Build benchmarks
        run: ./gradlew mainBenchmarkJar

      - name: Run benchmarks
        run: |
          OUT_FILE_NAME=$(date "+%Y-%m-%dT%H%M%S-linux-x64-"$(git rev-parse --short HEAD)".json")
          test -d results || mkdir results
          java -jar ./jvm-benchmarks/build/benchmarks/main/jars/jvm-benchmarks-main-jmh-JMH.jar -f2 -rf json -tu ns -bm avgt -rff results/$OUT_FILE_NAME

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'

  native-linux-x86:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'liberica'
          architecture: x64

      - name: Run benchmarks
        run: ./gradlew linuxX64Benchmark

      - name: Copy results
        run: |
          REPORTS_DIR=kmp-benchmarks/build/reports/benchmarks/main/
          DIR_NAME=$(ls $REPORTS_DIR | head -n1)
          ls $REPORTS_DIR/$DIR_NAME/*.json | while read report_json; do arch_name=$(basename $report_json); cp $report_json results/$DIR_NAME-kn-$arch_name; done

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'
  js-linux-x86:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'liberica'
          architecture: x64

      - name: Run benchmarks
        run: ./gradlew jsBenchmark

      - name: Copy results
        run: |
          REPORTS_DIR=kmp-benchmarks/build/reports/benchmarks/main/
          DIR_NAME=$(ls $REPORTS_DIR | head -n1)
          ls $REPORTS_DIR/$DIR_NAME/*.json | while read report_json; do arch_name=$(basename $report_json); cp $report_json results/$DIR_NAME-kn-$arch_name; done

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'
  wasmJs-linux-x86:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'liberica'
          architecture: x64

      - name: Run benchmarks
        run: ./gradlew wasmJsInt.baselineBenchmark wasmJsLong.baselineBenchmark wasmJsInt.bitmanipBenchmark wasmJsLong.bitmanipBenchmark

      - name: Copy results
        run: |
          REPORTS_DIR=kmp-benchmarks/build/reports/benchmarks/
          ls $REPORTS_DIR | while read CONFIG_DIR; do
            DIR_NAME=$(ls $REPORTS_DIR/$CONFIG_DIR | head -n1)
            ls $REPORTS_DIR/$CONFIG_DIR/$DIR_NAME/*.json | while read report_json; do 
              arch_name=$(basename $report_json); 
              cp $report_json results/$DIR_NAME-$CONFIG_DIR-kn-$arch_name;
            done
          done

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'
